// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd0aeDEnHmjsR8XArbjPZVyyHgrmJjT14',
    appId: '1:796438372620:web:5cccabd7983d016004a929',
    messagingSenderId: '796438372620',
    projectId: 'projectd-a2f3e',
    authDomain: 'projectd-a2f3e.firebaseapp.com',
    storageBucket: 'projectd-a2f3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyKo6gXb1zqizQNITHpD4e_c-uxfVDcDU',
    appId: '1:796438372620:android:92fede88d89d1b0704a929',
    messagingSenderId: '796438372620',
    projectId: 'projectd-a2f3e',
    storageBucket: 'projectd-a2f3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBor6sR7sPL7yu-18UF3kHZyvwV8HGgV-0',
    appId: '1:796438372620:ios:08f4e5bc8809b38804a929',
    messagingSenderId: '796438372620',
    projectId: 'projectd-a2f3e',
    storageBucket: 'projectd-a2f3e.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMessage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBor6sR7sPL7yu-18UF3kHZyvwV8HGgV-0',
    appId: '1:796438372620:ios:1ad4e776ec7088cb04a929',
    messagingSenderId: '796438372620',
    projectId: 'projectd-a2f3e',
    storageBucket: 'projectd-a2f3e.appspot.com',
    iosBundleId: 'com.example.flutterApplicationMessage.RunnerTests',
  );
}
